version: '3'

tasks:
  default:
    cmds:
      - task: pull
      - task: build
      - task: start

  pull:
    desc: Pull Docker images from registry
    cmd: docker compose pull

  build:
    desc: Build local Docker images
    cmd: docker compose build

  start:
    desc: Create and start containers detached
    cmd: docker compose up -d

  composer:
    desc: Run Composer command
    cmd: docker compose --profile cli run --rm composer {{.CLI_ARGS}}

  symfony:
    desc: Run Symfony command
    cmd: docker compose --profile cli run --rm composer {{.CLI_ARGS}}

  console:
    desc: Run console command
    cmd: docker compose --profile cli run --rm composer {{.CLI_ARGS}}
